export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const GET_MAKERS_WITH_FILTERS = 'GET_MAKERS_WITH_FILTERS';
export const GET_MAKER_PRODUCTS = 'GET_MAKER_PRODUCTS';
export const IS_FETCHING_CATEGORIES = 'IS_FETCHING_CATEGORIES';
export const IS_FETCHING_MAKERS = 'IS_FETCHING_MAKERS';
export const IS_FETCHING_MAKER = 'IS_FETCHING_MAKER';
